export const ACTIONS = {
    SET_TASKS: 'SET_TASKS',
    SET_LOGIN_FORM_OPEN: 'SET_LOGIN_FORM_OPEN',
    SET_TASK_FORM_OPEN: 'SET_TASK_FORM_OPEN',
    SET_IS_ADMIN: 'SET_IS_ADMIN',
    SET_TOTAL: 'SET_TOTAL',
    SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
    SET_CURRENT_TASK: 'SET_CURRENT_TASK',
    SET_SORT_DIRECTION: 'SET_DIRECTION',
    SET_SORT_FIELD: 'SET_FIELD',
    SET_USER_MESSAGE: 'SET_USER_MESSAGE',
};